import { Upgrade } from '../types/game';

export const INITIAL_UPGRADES: Upgrade[] = [
  {
    id: 'better-racket',
    name: 'Mejor Raqueta',
    description: '+1 punto por golpe',
    icon: '🏓',
    baseCost: 15,
    costMultiplier: 1.5,
    level: 0,
    maxLevel: 50,
    effect: 'clickPower',
    effectValue: 1,
  },
  {
    id: 'ball-machine',
    name: 'Lanzapelotas',
    description: '+1 punto por segundo',
    icon: '⚙️',
    baseCost: 50,
    costMultiplier: 1.6,
    level: 0,
    maxLevel: 30,
    effect: 'autoClick',
    effectValue: 1,
  },
  {
    id: 'pro-grip',
    name: 'Grip Pro',
    description: '+3 puntos por golpe',
    icon: '🤚',
    baseCost: 200,
    costMultiplier: 1.7,
    level: 0,
    maxLevel: 25,
    effect: 'clickPower',
    effectValue: 3,
  },
  {
    id: 'training-partner',
    name: 'Compañero de Entrenamiento',
    description: '+5 puntos por segundo',
    icon: '🧑‍🤝‍🧑',
    baseCost: 500,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 20,
    effect: 'autoClick',
    effectValue: 5,
  },
  {
    id: 'golden-ball',
    name: 'Pelota Dorada',
    description: 'x2 multiplicador',
    icon: '✨',
    baseCost: 1000,
    costMultiplier: 2.5,
    level: 0,
    maxLevel: 10,
    effect: 'multiplier',
    effectValue: 1,
  },
  {
    id: 'pro-coach',
    name: 'Entrenador Pro',
    description: '+10 puntos por golpe',
    icon: '🎓',
    baseCost: 5000,
    costMultiplier: 2.0,
    level: 0,
    maxLevel: 15,
    effect: 'clickPower',
    effectValue: 10,
  },
  {
    id: 'padel-court',
    name: 'Tu Propia Cancha',
    description: '+25 puntos por segundo',
    icon: '🏟️',
    baseCost: 15000,
    costMultiplier: 2.2,
    level: 0,
    maxLevel: 10,
    effect: 'autoClick',
    effectValue: 25,
  },
];
